config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  get '/home' => 'page#home'
  get '/shop' => 'page#index'
  get '/product/:id' => 'page#product', as: :product
  get '/about' => 'page#about'

  namespace :admin do
    resources :brands
    resources :products
    resources :categories
  end

  resources :line_items, only: [:create]

  resource :cart, only: [:edit, :update, :destroy]

  resources :orders, only: [:new, :create, :show]

   root 'page#home'

end

app/models/brand.rb
class Brand < ActiveRecord::Base
   has_many :products

   validates_uniqueness_of :name
end

app/models/cart.rb
class Cart < ActiveRecord::Base
  has_many :line_items, dependent: :destroy


  # def subtotal
  #   line_items.to_a.sum{|item| item.total}
  # end

  #SQL version of summing, faster than Ruby
  def subtotal
    line_items.select("SUM(quantity * price) as sum")[0].sum
  end

  # def tax
  #   subtotal * 0.09
  # end

  def total
    subtotal
    # + tax
  end

# Finds if product is already in cart
  def add_product(product_id)
    product = Product.find(product_id)
    current_item = line_items.find_by(product_id: product_id)

    #If current_item is there, increase quantity. If not, build new line item
    if current_item
      current_item.quantity += 1
      else
        current_item = line_items.build(product: product, price: product.current_price)
    end

    current_item

  end

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :products

  validates_uniqueness_of :name
end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
  belongs_to :product
  belongs_to :cart
  belongs_to :order

  def total
    price * quantity
  end

  #TODO before save, reduce product inventory quantity
  #TODO before delete action that updates product inventory quantity (when removed from cart)
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :user
  has_many :line_items

  validates_presence_of :shipping_name, :shipping_address, :payment_type

  PAYMENT_TYPES = ["Credit Card", "Paypal", "Bitcoin"]
  validates_inclusion_of :payment_type, in: PAYMENT_TYPES

  def add_line_items_from_cart(cart)
    cart.line_items.each do |item|
      item.cart_id = nil
      line_items << item
    end
  end

  def subtotal
    line_items.select("SUM(quantity * price) as sum")[0].sum
  end

  # def tax
  #   subtotal * 0.09
  # end

  def total
    subtotal
    # + tax
  end

end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :brand
  belongs_to :category

  has_many :line_items
  before_destroy :ensure_not_referenced_by_line_items

  has_attached_file :avatar, styles: { large: "500x500#", medium: "300x300#", thumb: "100x100#" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/

  validates_presence_of :name, :current_price, :quantity, :description, :brand, :category

  validates_numericality_of :current_price, greater_than_or_equal_to: 0.01

  validates_numericality_of :quantity, greater_than_or_equal_to: 0
#     t.string   "name"
#     t.decimal  "current_price"
#     t.integer  "quantity"
#     t.text     "description"
#     t.integer  "brand_id"
#     t.integer  "category_id"
#     t.datetime "created_at",          null: false
#     t.datetime "updated_at",          null: false
#     t.string   "avatar_file_name"
#     t.string   "avatar_content_type"
#     t.integer  "avatar_file_size"
#     t.datetime "avatar_updated_at

  def self.search_by_name_or_desc(string)
    where("name LIKE ? OR description LIKE ?", "%#{string}%", "%#{string}%")
  end

  def self.featured
    all.sample(3)
  end

  private

  def ensure_not_referenced_by_line_items
    if line_items.empty?
      return true
    else
      errors.add(:base, "Cannot delete. This product has line items present in orders")
      return false
    end
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :orders
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
 before_action :authenticate_user!
 before_action :require_admin_user
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  include CurrentCart
  before_action :set_cart

  def edit
  end

  def update
  end

  def destroy
    if @cart.destroy
      flash[:notice] = "Cart successfully emptied"
      session[:cart_id] = nil
      redirect_to shop_url
    else
      flash[:alert] = "Sorry Dave, I can't let you do that."
      redirect_to edit_cart_url
    end
  end

end

app/controllers/line_items_controller.rb
class LineItemsController < ApplicationController
  include CurrentCart
  before_action :set_cart

  def create
    product = Product.find(params[:product_id])
    @line_item = @cart.add_product(product.id)

    if @line_item.save
      flash[:notice] = "#{product.name} was successfully added to your cart!"
      redirect_to shop_url
    else
      flash.now[:alert] = "Could not add #{product.name} to your cart. Sorry."
      redirect_to :back
    end
  end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  include CurrentCart
  before_action :authenticate_user!
  before_action :set_cart, only: [:new, :create]
  def new
    if @cart.line_items.empty?
      redirect_to shop_url, notice: "Your cart is empty."
      return
    end

    @order = Order.new

  end

  def create
    @order = current_user.orders.build(order_params)

    if @order.save
      # Move items from cart to order
      @order.add_line_items_from_cart(@cart)

      # Destroy the cart and reset the session cart_id
      Cart.destroy(session[:cart_id])
      session[:cart_id] = nil

      # Send confirmation email
      OrderConfirmation.send_order_confirmation(current_user, @order).deliver_now

      # Redirect and confirmation notice
      redirect_to @order, notice: "Thank you for your order!"

    else
      render :new
    end
  end

  def show
    #TODO: deny access to other users' orders
    @order = Order.find(params[:id])
  end

  private

  def order_params
    params.require(:order).permit(:shipping_name, :shipping_address, :payment_type)
  end

end

app/controllers/page_controller.rb
class PageController < ApplicationController
  def home
    @featured_products = Product.featured
  end

  def index
    if params[:search]
      @products=Product.search_by_name_or_desc(params[:search]).includes(:brand)
      if @products.empty?
        flash.now[:notice] = "No result found for \"#{params[:search]}\", here's the rest of our products."
        @products=Product.includes(:brand)
      end
    elsif params[:category_id]
      @category=Category.find(params[:category_id])
      @products=Product.where(category_id: @category.id).includes(:brand)
    else
    @products = Product.includes(:brand)
    end
  end

  def about
  end

  def product
    @product = Product.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/_admin_links.html.erb
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Admin<span class="caret"></span></a>
  <ul class="dropdown-menu">
    <li><%= link_to "Categories", admin_categories_path %></li>
    <li><%= link_to "Brands", admin_brands_path %></li>
    <li><%= link_to "Products", admin_products_path %></li>
  </ul>
</li>

app/views/layouts/_messages.html.erb
<% if notice %>
<div class="alert alert-success" role="alert">
  <p><%= notice %></p>
</div>
<% elsif alert %>
<div class="alert alert-warning" role="alert">
  <p><%= alert %></p>
</div>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "CoolPups", root_path, class:"navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

      <%= render 'layouts/navbar_links' %>

    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/_navbar_links.html.erb
<ul class="nav navbar-nav">
  <li><%= link_to "Shop", shop_path%></li>
  <li class="dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Shop Categories<span class="caret"></span></a>
    <ul class="dropdown-menu">
    <!-- loop through each category to get name and link -->
     <% Category.order(:name).each do |category| %>
      <li><%= link_to category.name.titleize, shop_path(category_id: category.id)%></li>
     <% end %>

      <li role="separator" class="divider"></li>
      <li><%= link_to 'All Products', shop_path %></li>
    </ul>
  </li>
  <li><%= link_to "About", about_path %></li>
</ul>

<ul class="nav navbar-nav navbar-right">
  <% if session[:cart_id] %>
    <li><%= link_to fa_icon('shopping-cart', text:'Cart'), edit_cart_path %></li>
  <% end %>
  <% if user_signed_in? %>
    <li><%= link_to fa_icon('gear', text:'Your Account'), edit_user_registration_path %></li>
    <li><%= link_to fa_icon('sign-out', text:'Log Out'), destroy_user_session_path, method: :delete %></li>
  <% else %>
    <li><%= link_to fa_icon('user-plus', text: "Sign Up"), new_user_registration_path %> </li>
    <li><%= link_to fa_icon('sign-in', text: 'Sign In'), new_user_session_path %></li>
  <% end %>

  <!-- Admin dropdown -->
  <% if user_signed_in? && current_user.admin %>
    <%= render 'layouts/admin_links' %>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Storefront</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <%= render 'layouts/navbar' %>

  <div class="container-fluid">
    <%= render 'layouts/messages' %>
    <%= yield %>
  </div>

</body>
</html>

app/views/order_confirmation/send_order_confirmation.html.erb
<h1>Thanks for your order, <%= @user.email %>!</h1>

<p>Your order number: <%= @order.id %></p>
<p>Your total: <%= @order.subtotal %></p>

app/views/order_confirmation/send_order_confirmation.text.erb
Thanks for your order, <%= @user.email %>!


Your order number: <%= @order.id %>

Your total: <%= @order.subtotal %>

app/views/page/_carousel.html.erb
<div id="carousel-example-generic" class="carousel slide" data-ride="carousel" data-interval="3000">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
    <li data-target="#carousel-example-generic" data-slide-to="1"></li>
    <li data-target="#carousel-example-generic" data-slide-to="2"></li>
  </ol>

  <!-- Wrapper for slides -->
  <div class="carousel-inner" role="listbox">
    <% @featured_products.each_with_index do |featured, index| %>
     <div class="item <%= 'active' if index == 0 %> text-center">
      <%= link_to (image_tag featured.avatar.url(:medium)), product_path(featured.id) %>
      <div class="carousel-caption">
        <%= featured.name %>
      </div>
    </div>
    <% end %>
  </div>

  <!-- Controls -->
  <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

app/views/page/_search_form.html.erb
<span class="pull-right">
  <%= form_tag(shop_path, method: :get, role: "search", class:"form-inline") do %>
    <div class="form-group">
      <!-- <%= label_tag fa_icon('search') %> -->
      <i class="fa fa-search fa-lg"></i>
      <%= text_field_tag(:search, nil, placeholder: "Search Store", class: "form-control input-sm") %>
    </div>
    <%= submit_tag("Search", class: "btn btn-primary btn-sm", id: "search_button") %>
  <% end %>
</span>

app/views/page/about.html.erb
<h1> About </h1>

app/views/page/home.html.erb
</div>

<div class="container text-center welcome">
  <h1>Welcome to CoolPups</h1>
  <h3>We make your pups look really cool</h3>
  <%= link_to "Click to shop", shop_path, class: "btn btn-lg btn-success" %>
</div>

<div class="container">

app/views/page/index.html.erb
<!-- search bar -->
<%= render 'search_form' %>

<% if params[:category_id] %>
  <h3>All <%= @category.name.titleize %></h3>
<% else %>
  <h3>All Products</h3>
<% end %>
<div class="row">
 <%= render @products %>
</div>

app/views/page/product.html.erb
<div class="row">
  <div class="col-sm-7">
    <%= image_tag @product.avatar.url(:large), class: "img-responsive" %>
  </div>
  <div class="col-sm-5">
    <h3><%= @product.name %></h3>
    <h4>by <%= @product.brand.try(:name) %></h4>
    <p><%= @product.description %></p>
    <h3>Price: <span class="prices"><%= number_to_currency @product.current_price %></span></h3>

    <%= button_to "Add to Cart", line_items_path(product_id: @product.id), class:"btn btn-lg btn-success" %>
  </div>
</div>